<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_55c40196c888f',
	'title' => 'Repeater Banners',
	'fields' => array (
		array (
			'key' => 'field_55c401c3ddc01',
			'label' => 'Location',
			'name' => 'location',
			'prefix' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'front-page' => 'Home Page',
				'products' => 'Product Page',
				'good-green-stuff' => 'Good Green Stuff Page',
				'clean-lean-protein' => 'Clean Lean Protein Page',
				'kids-good-stuff' => 'Kids Good Stuff Page',
				'shop' => 'Shop',
				'blog' => 'Blog',
				'recipes' => 'Recipes',
			),
			'default_value' => array (
				'' => '',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_55c40209ddc02',
			'label' => 'Slides',
			'name' => 'small_banners',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => 'Create your banner slides below. Only those marked "Active" will be displayed on the page. Try to limit the number of active slides to no more than 4 at a time to optimize your page load speed.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '!=',
						'value' => 'front-page',
					),
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '!=',
						'value' => 'products',
					),
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '!=',
						'value' => 'good-green-stuff',
					),
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '!=',
						'value' => 'clean-lean-protein',
					),
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '!=',
						'value' => 'kids-good-stuff',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => 'small_banners',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_65d123161a422',
					'label' => 'Image',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_55c405c82c2b4',
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'prefix' => '',
					'type' => 'image',
					'instructions' => 'Select an image. Min width 1160px. Accepted file types are .jpg, .jpeg, .gif and .png',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '90',
						'class' => '',
						'id' => 'banner_image',
					),
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => 1160,
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .jpeg, .png, .gif',
				),
				array (
					'key' => 'field_55c405b72c2b3',
					'label' => 'Active',
					'name' => 'active',
					'prefix' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '10',
						'class' => '',
						'id' => 'active',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_99d123520a423',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
							array (
					'key' => 'field_55c405f72c2b5',
					'label' => 'Recipe Link',
					'name' => 'recipe_link',
					'prefix' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'recipes',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => 'recipe_link',
					),
					'post_type' => array (
						0 => 'recipes',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_55c4063a2c2b6',
					'label' => 'Post Link',
					'name' => 'post_link',
					'prefix' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'blog',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => 'post_link',
					),
					'post_type' => array (
						0 => 'post',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_55d2907fc51d0',
					'label' => 'Banner Content',
					'name' => 'get_post_content',
					'type' => 'radio',
					'instructions' => 'Use the post title and excerpt or write your own banner content. Note that any author information will be automatically generated from the blog post.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'blog',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'post' => 'Generate From Post',
						'custom' => 'Custom Text',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'post',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_27d2907fc61d0',
					'label' => 'Slide Content',
					'name' => 'get_recipe_content',
					'type' => 'radio',
					'instructions' => 'Use recipe title and excerpt or write your own banner content. Note that any dietary requirement tags will be automatically generated from the recipe post.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'recipes',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'post' => 'Generate From Post',
						'custom' => 'Custom Text',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'post',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_55c406562c2b7',
					'label' => 'Link',
					'name' => 'shop_link',
					'prefix' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'shop',
							),
						),
					),
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => 'shop_link',
					),
					'post_type' => array (
						0 => 'product',
						1 => 'page',
						2 => 'post',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_55cbd573ae10f',
					'label' => 'Button Colour',
					'name' => 'button_colour',
					'prefix' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'shop',
							),
						),
					),
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'primary' => 'Green',
						'orange' => 'Orange',
						'purple' => 'Purple',
					),
					'default_value' => array (
						'' => '',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55cbd5b4ae110',
					'label' => 'Button Text',
					'name' => 'button_text',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '!=',
								'value' => 'blog',
							),
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '!=',
								'value' => 'recipes',
							),
						),
					),
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55c40d4e2c2ba',
					'label' => 'Banner Heading',
					'name' => 'banner_heading',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'shop',
							),
						),
						array (
							array (
								'field' => 'field_55d2907fc51d0',
								'operator' => '==',
								'value' => 'custom',
							),
						),
						array (
							array (
								'field' => 'field_27d2907fc61d0',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => 'banner_heading',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55c40d7e2c2bb',
					'label' => 'Banner Content',
					'name' => 'banner_content',
					'prefix' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c401c3ddc01',
								'operator' => '==',
								'value' => 'shop',
							),
						),
						array (
							array (
								'field' => 'field_55d2907fc51d0',
								'operator' => '==',
								'value' => 'custom',
							),
						),
						array (
							array (
								'field' => 'field_27d2907fc61d0',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array (
						'width' => '100',
						'class' => '',
						'id' => 'banner_content',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_55c40223ddc03',
			'label' => 'Slides',
			'name' => 'wide_banners',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => 'Create your banner slides below. Only those marked "Active" will be displayed on the page. Try to limit the number of active slides to no more than 4 at a time to optimize your page load speed.',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '==',
						'value' => 'front-page',
					),
				),
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '==',
						'value' => 'products',
					),
				),
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '==',
						'value' => 'good-green-stuff',
					),
				),
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '==',
						'value' => 'clean-lean-protein',
					),
				),
				array (
					array (
						'field' => 'field_55c401c3ddc01',
						'operator' => '==',
						'value' => 'kids-good-stuff',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => 'wide_banners',
			),
			'min' => '',
			'max' => '',
			'layout' => 'block',
			'button_label' => 'Add Slide',
			'sub_fields' => array (
				array (
					'key' => 'field_55d267161e424',
					'label' => 'Image',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_55c402d1ddc0d',
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'prefix' => '',
					'type' => 'image',
					'instructions' => 'Add an image. Min width 2560px. Accepted file types are .jpg, .jpeg, .gif and .png',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '90',
						'class' => '',
						'id' => 'banner_image',
					),
					'return_format' => 'array',
					'preview_size' => 'full',
					'library' => 'all',
					'min_width' => 2560,
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '.jpg, .jpeg, .png, .gif',
				),
				array (
					'key' => 'field_55c4035fddc0e',
					'label' => 'Active',
					'name' => 'active',
					'prefix' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '10',
						'class' => '',
						'id' => 'active',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_55d2673a1e425',
					'label' => 'Content',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_55c4037cddc0f',
					'label' => 'Banner Heading',
					'name' => 'banner_heading',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => 'banner_heading',
					),
					'default_value' => '',
					'placeholder' => 'Banner Heading',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55c40396ddc10',
					'label' => 'Banner Content',
					'name' => 'banner_content',
					'prefix' => '',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => 'banner_content',
					),
					'default_value' => '',
					'placeholder' => 'Banner content',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => 'br',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55c403b3ddc11',
					'label' => 'Button Link',
					'name' => 'button_link',
					'prefix' => '',
					'type' => 'post_object',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '40',
						'class' => '',
						'id' => 'button_link',
					),
					'post_type' => array (
						0 => 'page',
						1 => 'post',
						2 => 'product',
						3 => 'recipes',
					),
					'taxonomy' => '',
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_55c4042addc13',
					'label' => 'Button Text',
					'name' => 'button_text',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => 'button_text',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55c40407ddc12',
					'label' => 'Button Colour',
					'name' => 'button_colour',
					'prefix' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => 'button_colour',
					),
					'choices' => array (
						'primary' => 'Green',
						'orange' => 'Orange',
						'purple' => 'Purple',
					),
					'default_value' => array (
						'' => '',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55d2698a1e426',
					'label' => 'Responsive Layout',
					'name' => '',
					'type' => 'tab',
					'instructions' => 'Use this section if you are familiar with designing layouts for the web.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'field_55c40440ddmlb',
					'label' => 'Image Crop Mobile',
					'name' => 'image_crop_mobile',
					'prefix' => '',
					'type' => 'select',
					'instructions' => 'Point to crop image from on mobile',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => 'image_crop',
					),
					'choices' => array (
						'm-crop-hard-left' => 'Hard Left',
						'm-crop-left' => 'Left (default)',
						'm-crop-mid' => 'Middle',
						'm-crop-right' => 'Right',
						'm-crop-hard-right' => 'Hard Right',
					),
					'default_value' => array (
						'm-crop-left' => 'Left (default)',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55c40440ddc14',
					'label' => 'Image Crop Larger',
					'name' => 'image_crop',
					'prefix' => '',
					'type' => 'select',
					'instructions' => 'Point to crop image from on larger screens',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => 'image_crop',
					),
					'choices' => array (
						0 => 'Hard Left',
						25 => 'Left',
						50 => 'Middle',
						75 => 'Right (default)',
						100 => 'Hard Right',
					),
					'default_value' => array (
						75 => 'Right (default)',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
				array (
					'key' => 'field_55c4099692704',
					'label' => 'Hide text on mobile?',
					'name' => 'hide_text',
					'prefix' => '',
					'type' => 'true_false',
					'instructions' => 'Check if text overlaps image on mobile',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '20',
						'class' => '',
						'id' => 'active',
					),
					'message' => '',
					'default_value' => 0,
				),
				array (
					'key' => 'field_55c40486cd7f5',
					'label' => 'Text Placement',
					'name' => 'text_placement',
					'prefix' => '',
					'type' => 'radio',
					'instructions' => 'Where should the content be positioned?',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '30',
						'class' => '',
						'id' => 'Text Placement',
					),
					'choices' => array (
						'left' => 'Left',
						'right' => 'Right',
						'custom' => 'Custom',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => array (
						'right' => 'Right',
					),
					'layout' => 'horizontal',
				),
				array (
					'key' => 'field_55c40499cd7f6',
					'label' => 'Custom Scaling',
					'name' => 'custom_scaling',
					'prefix' => '',
					'type' => 'repeater',
					'instructions' => 'Specify how text should display on different devices using custom Bootstrap classes',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_55c40486cd7f5',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'min' => '',
					'max' => 6,
					'layout' => 'table',
					'button_label' => 'Add Media Breakpoint',
					'sub_fields' => array (
						array (
							'key' => 'field_55c404c9cd7f7',
							'label' => 'Device Size',
							'name' => 'device_size',
							'prefix' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'xs' => 'Phone (xs)',
								'sm' => 'Tablet (sm)',
								'md' => 'Sm Desktop (md)',
								'lg' => 'Lg Desktop (lg)',
								'xl' => 'XL Desktop (xl)',
								'xxl' => 'Widescreen (xxl)',
							),
							'default_value' => array (
								'' => '',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'disabled' => 0,
							'readonly' => 0,
						),
						array (
							'key' => 'field_55c404ebcd7f8',
							'label' => 'Width',
							'name' => 'width',
							'prefix' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'cols',
							'min' => 0,
							'max' => 12,
							'step' => 1,
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55c40506cd7f9',
							'label' => 'Offset',
							'name' => 'offset',
							'prefix' => '',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'cols',
							'min' => 0,
							'max' => 8,
							'step' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'banners',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
));

endif;
