<?php
if( function_exists('register_field_group') ):
  register_field_group(array (
    'id' => 'store-location',
    'title' => __('Stockist Location', 'store'),
    'fields' => array (
      array (
        'key' => 'store_location',
        'label' => __('Location', 'store'),
        'name' => 'location',
        'type' => 'google_map',
        'required' => 1,
        'val' => 'address',
        'mapheight' => 300,
        'center' => '-33.8587,151.2140',
        'zoom' => 12,
        'scrollwheel' => 1,
        'mapTypeControl' => 1,
        'streetViewControl' => 1,
        'PointOfInterest' => 1,
      ),
      array (
        'key' => 'store_street',
        'label' => __('Street Address', 'store'),
        'name' => 'street_address',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_city',
        'label' => __('City', 'store'),
        'name' => 'city',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_state',
        'label' => __('State', 'store'),
        'name' => 'state',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_zip',
        'label' => __('Postcode', 'store'),
        'name' => 'zip_code',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_phone',
        'label' => __('Phone', 'store'),
        'name' => 'phone',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_fax',
        'label' => __('Fax', 'store'),
        'name' => 'fax',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
      array (
        'key' => 'store_url',
        'label' => __('Website', 'store'),
        'name' => 'url',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => 'www.example.com.au',
        'prepend' => 'http://',
        'append' => '',
        'formatting' => 'none',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'stores',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => array (
      0 => 'the_content',
      1 => 'excerpt',
      2 => 'discussion',
      3 => 'comments',
      4 => 'revisions',
      5 => 'author',
      6 => 'format',
      7 => 'page_attributes',
      8 => 'featured_image',
      9 => 'categories',
      10 => 'tags',
      11 => 'send-trackbacks',
    ),
  ));
endif;
